// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9Uw7maZ-u60fjLb4VDGdAyI3LOFSmfdA',
    appId: '1:497619749034:web:23c7891754dbc01fbd68d3',
    messagingSenderId: '497619749034',
    projectId: 'indagram-31d57',
    authDomain: 'indagram-31d57.firebaseapp.com',
    storageBucket: 'indagram-31d57.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATRoZCTNpHoqJkWWuUv4DQPBVhv6K1Cpc',
    appId: '1:497619749034:android:6d04ee912562e1d1bd68d3',
    messagingSenderId: '497619749034',
    projectId: 'indagram-31d57',
    storageBucket: 'indagram-31d57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-HReaM-WaBBsyUgPNx6mE4C62ck0hQm0',
    appId: '1:497619749034:ios:bb16cdf9f367d16bbd68d3',
    messagingSenderId: '497619749034',
    projectId: 'indagram-31d57',
    storageBucket: 'indagram-31d57.appspot.com',
    iosClientId: '497619749034-jljdatejuqd9ph65sn23mfhjd3ga1etq.apps.googleusercontent.com',
    iosBundleId: 'com.example.indagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-HReaM-WaBBsyUgPNx6mE4C62ck0hQm0',
    appId: '1:497619749034:ios:e5fbf85eb6956c23bd68d3',
    messagingSenderId: '497619749034',
    projectId: 'indagram-31d57',
    storageBucket: 'indagram-31d57.appspot.com',
    iosClientId: '497619749034-1ukru6b2dk7aald9s443dtqepu53infh.apps.googleusercontent.com',
    iosBundleId: 'com.example.indagram.RunnerTests',
  );
}
